[head]
carrier.cluster.local ansible_host=192.168.50.1

[management]
arbiter.cluster.local ansible_host=192.168.50.50 ansible_connection=local

[workers]
interceptor-01.cluster.local ansible_host=192.168.50.15
interceptor-02.cluster.local ansible_host=192.168.50.32

[gpu]
corsair-01.cluster.local ansible_host=192.168.50.11

[visualization]
observer.cluster.local ansible_host=192.168.50.19

[compute:children]
workers
gpu

[all_nodes:children]
head
management
workers
gpu
visualization

[workers:vars]
ansible_user=wpaik

[all_nodes:vars]
ansible_user=wpaik
cluster_network=192.168.50.0/24
cluster_domain=cluster.local
cluster_realm=CLUSTER.LOCAL
