# /etc/dnsmasq.conf
# Replace <WIRED INTERFACE> with the output of `nmcli device`

interface=<WIRED INTERFACE>
dhcp-range=192.168.50.10,192.168.50.50,12h
dhcp-option=3,192.168.50.1
dhcp-option=6,1.1.1.1,8.8.8.8

# Comment out once the cluster is stable
log-queries
log-dhcp
