# slurmdbd.conf
# WARNING: This file must be mode 600 and owned by the slurm user
#   sudo chown slurm:slurm /etc/slurm/slurmdbd.conf
#   sudo chmod 600 /etc/slurm/slurmdbd.conf

AuthType=auth/munge
DbdHost=arbiter
DbdPort=6819
StorageType=accounting_storage/mysql
StorageHost=localhost
StoragePort=3306
StorageUser=slurm
StoragePass=YOUR_DB_PASSWORD_HERE
StorageLoc=slurm_acct_db
LogFile=/var/log/slurm/slurmdbd.log
PidFile=/run/slurm/slurmdbd.pid
SlurmUser=slurm
