# Created by `sudo systemctl edit sshd.service`
# Path: /etc/systemd/system/sshd.service.d/override.conf

[Unit]
Wants=network-online.target
After=network-online.target

[Service]
Restart=on-failure
RestartSec=5s
StartLimitIntervalSec=0
